/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HatsGatekeeperBase } from "./HatsGatekeeperBase";
export type { HatsGatekeeperMultiple } from "./HatsGatekeeperMultiple";
export type { HatsGatekeeperSingle } from "./HatsGatekeeperSingle";
